services:
  # server:
  #   build:
  #     context: ./sync-server
  #     dockerfile: Dockerfile
  #   networks:
  #     - local_network

  server:
    build:
      context: ./async-server
      dockerfile: Dockerfile
    networks:
      - local_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    deploy:
      replicas: 5
    networks:
      - local_network
    depends_on:
      - server

networks:
  local_network:
    driver: bridge